[package]
name = "fib"
version = "0.1"
lean_version = "leanprover-community-lean-nightly"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "a33315d594731876aa780bb12fc79b3e67198302"}
