[package]
name = "fib"
version = "0.1"
lean_version = "leanprover-community/lean:3.22.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "d9c82152cb9036038916d25bf0143a8535654500"}
