[package]
name = "fib"
version = "0.1"
lean_version = "leanprover-community/lean:3.6.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "093ac77ac9d27ce83ebf4e76ca5bd9b3eaebedaa"}
