[package]
name = "fib"
version = "0.1"
lean_version = "leanprover-community/lean:3.23.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "58f8817e6aff0abdf7bc294ef72c3e441db151ab"}
