[package]
name = "fib"
version = "0.1"
lean_version = "leanprover-community/lean:3.17.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "d0df6b81cd0920ad569158c06a3fd5abb9e63301"}
