[package]
name = "fib"
version = "0.1"
lean_version = "leanprover-community/lean:3.20.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "38d1715b92fbe74ca071593b521cab2283f7e968"}
