[package]
name = "fib"
version = "0.1"
lean_version = "leanprover-community/lean:3.14.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "a9960ceffff8577750080d5fce05581ab35bd8ce"}
